packages:
  # include packages in subfolders (change as required)
  - "apps/**"
  - "packages/**"
  # if required, exclude directories
  - "!**/test/**"
publicHoistPattern:
  - "*import-in-the-middle*"
  - "*require-in-the-middle*"
